### ISSUE TITLE
Last character emitted when `selection` is set to `exclusive`

### ISSUE THREAD

**Issue by idanarye** [machakann/vim-swap#1]
With `set selection=exclusive`:

```
foo(aa, bb)
    ^
    |
  cursor
```

When I type `g>` to swap `aa` with `bb`, I get:

```
foo(b, aa)
```

The last `b` was deleted.

With `set selection=inclusive` or `set selection=old` it works fine.

**Comment by machakann** [comment]
Thank you for your report. Now I have modified with ca3f87d06c7a84f571c83097fd583ec5d4dd1a86, could you try?

**Comment by idanarye** [comment]
Perfect!
