### ISSUE TITLE
Exposing around/inside selectors

### ISSUE THREAD

**Issue by mibli** [machakann/vim-swap#12]
Hey, this plugin is super cool, I'm just wondering whether it was possible to use it's internals for selecting around and inside of function parameters.

Eg: in situation where foo(bar, a|sd), where | is Your pointer. You'd press `da,` (delete around parameter), and it would delete ", asd". Similarily having cursor on foo(ba|r, asd) and pressing `da,` would delete "bar, ".

Not sure if Your code allows that, but it doesn't hurt to ask :)

**Comment by machakann** [comment]
Probably, what you are searching for is:

```vim
omap i, <Plug>(swap-textobject-i)
xmap i, <Plug>(swap-textobject-i)
omap a, <Plug>(swap-textobject-a)
xmap a, <Plug>(swap-textobject-a)
```

Isn't it?

**Comment by mibli** [comment]
That's exactly what I meant. I guess I've overlooked these in the README. Youre doing Gods work mate!
