### ISSUE TITLE
How can I define a rule to swap within | delimiters (markdown-like tables)?

### ISSUE THREAD

**Issue by habamax** [machakann/vim-swap#13]
I have tried to add a rule such as:

```
    let g:swap#rules = deepcopy(g:swap#default_rules)
    let g:swap#rules += [
                \   {
                \     'mode': 'n',
                \     'description': 'Reorder the | bar | delimited | things |.',
                \     'delimiter': ['\s*|\s*'],
                \     'priority': -100
                \   }]
```

Which doesn't work for me. With `g>` on a `world`:
```
 | world | hello |
```
I get `world` to be shifted on one space right:

```
 |  world| hello |
```

Thank you!

PS, also tired different combinations of delimiters with escaping `\|`, without `\s*`,  was also tried to add body but nothing worked for me :).

**Comment by machakann** [comment]
One important thing is either the `'body'` key or the `'braket'` key is necessary for a recipe with `'mode': 'n'`. Probably, the below one works.

```
    let g:swap#rules = deepcopy(g:swap#default_rules)
    let g:swap#rules += [
                \   {
                \     'mode': 'n',
                \     'description': 'Reorder the | bar | delimited | things |.',
                \     'body': '|\%([^|]\+|\)\+',
                \     'delimiter': ['\s*|\s*'],
                \     'priority': -40
                \   }]
```

I increased the priority because a default recipe with `'priority': -50` unintentionally interrupts your new recipe. So

> Which doesn't work for me. With g> on a world:
> 
>  | world | hello |
> 
> I get world to be shifted on one space right:
> 
>  |  world| hello |

this is maybe because of an improper recipe. I will fix it later.

**Comment by habamax** [comment]
So it was about body. Thx it works with your example.

**Comment by habamax** [comment]
It actually gives an error on interactive swap (when you press enter):

  
![image](https://user-images.githubusercontent.com/234774/110782299-05355600-8278-11eb-9c83-5c47ab315b3e.png)

**Comment by habamax** [comment]
It is probably a separate issue, because it fails for regular swaps (not the | )

**Comment by habamax** [comment]
Will open another one

**Comment by machakann** [comment]
Thanks, I will check.
