### ISSUE TITLE
error in interactive swap

### ISSUE THREAD

**Issue by habamax** [machakann/vim-swap#14]
# steps to reproduce

0. start `vim -Nu NONE`
1. `:packadd vim-swap`
2. add "hello, world" and start interactive swap on `hello`
3. then press `<CR>` and `l`

Errors pop up:

![vim-swap-issue2](https://user-images.githubusercontent.com/234774/110790562-3a46a600-8282-11eb-9153-894845936863.gif)

## vim version
* `windows: 8.2.2580`
* `debian wsl: 8.2.2589`

**Comment by machakann** [comment]
Thanks! Probably, fixed now.

**Comment by habamax** [comment]
Yes, indeed!
