### ISSUE TITLE
Bell may ring when using textobject

### ISSUE THREAD

**Issue by obcat** [machakann/vim-swap#17]
### Explain the issue

Using either `<Plug>(swap-textobject-i)` or `<Plug>(swap-textobject-a)` may cause the bell to be rung.

### To Reproduce

1. Write this in `/tmp/vimrc`:

    ```vim
    call delete('/tmp/vim-swap', 'rf')
    call system('git clone https://github.com/machakann/vim-swap.git /tmp/vim-swap')
    set runtimepath^=/tmp/vim-swap
    set debug=beep
    omap i, <Plug>(swap-textobject-i)
    ```

1. Write this in `/tmp/c.c`:

    ```c
    void foo() {
      bar(4, 2);
    }
    ```

1. Start Vim with this shell command:

    ```
    vim -Nu /tmp/vimrc /tmp/c.c
    ```

1. Press `/4<CR>` to move the cursor on the `4`.

1. Press `di,`.

    The `4` is deleted, but at that time the bell rings and `Beep!` is echo'ed on the command line.

### Expected behavior

Bell does not ring, `Beep!` is not echo'ed.

### Environment

 - vim-swap https://github.com/machakann/vim-swap/commit/e75fb91c4940447758902f8cab95d13f8be84d0e
 - Vim 8.2.3273
 - iTerm2
 - macOS Catalina (version 10.15.7)

**Comment by obcat** [comment]
Presumably the problem is that this `:normal! {count}h`:

https://github.com/machakann/vim-swap/blob/e75fb91c4940447758902f8cab95d13f8be84d0e/autoload/swap/lib.vim#L144-L146

is called when:

- `{count}` is positive
- cursor column is `1`
- 'whichwrap' is `b,s`

Maybe 'whichwrap' should be temporally set to `h,l`...?

**Comment by machakann** [comment]
Thanks!

**Comment by obcat** [comment]
Thanks too!
