### ISSUE TITLE
Customize mappings

### ISSUE THREAD

**Issue by rgrinberg** [machakann/vim-swap#2]
`gs` is already taken for me so I'd prefer to remap it to something else.

**Comment by machakann** [comment]
OK, please define `g:swap_no_default_key_mappings` in your vimrc, and remap what you need.

``` vim
let g:swap_no_default_key_mappings = 1
nmap gs <Plug>(swap-interactive)
xmap gs <Plug>(swap-interactive)
nmap g< <Plug>(swap-prev)
nmap g> <Plug>(swap-next)
```

Change `gs`, `g<` and `g>` to your preferable ones or just drop a line if you don't need it.

**Comment by rgrinberg** [comment]
Thank you very much
