### ISSUE TITLE
Swap mode doesn't work correctly for function calls with casted parameters

### ISSUE THREAD

**Issue by alexoj** [machakann/vim-swap#3]
With the following code:

```
void foo()
{
    bar(
        a,
        b,
        (int) c);
}
```

Using `gs` to swap `(int) c` and `a` results in:

```
void foo()
{
    bar(
        (int) c,
        b,
        a
}
```

The function call ending parenthesis and semicolon are missing.

**Comment by machakann** [comment]
Thank you, it was a bug of vim-swap.
Probably it is fixed in the latest commit. Could you test it?

**Comment by alexoj** [comment]
Seems to work fine now, thanks!

**Comment by machakann** [comment]
Good!
