### ISSUE TITLE
Use visual mode to limit scope of reordering in order to support reordering weird language constructs

### ISSUE THREAD

**Issue by alexanderbird** [machakann/vim-swap#4]
As a user of a language with unusual constructs, in order to use vim-swap with those language constructs, I would like the option to explicitly define the outer context of the delimited list before entering interactive reordering mode. 

Consider the TypeScript:
```
let something = someFunction(someVariable, ({ var1, var2}: { var1: any, var2: any[] }) => {
  return somethingElse;
});
```

When my cursor is overtop of the first occurrence of `var2`, I would like `g<` to move it to before var1. Instead, the anonymous function is reordered to before `someVariable`. I'm sure there are other examples in TypeScript or other languages where the standard parsing doesn't cut it. 

In order to take advantage of vim-swap in those corner cases, I suggest you add a binding for `gs` from visual mode - it would restrict the scope of the interactive reordering to the selected text. With this, I could select (in visual mode) from the first opening curly brace to the first closing curly brace (move cursor to the correct line; `f{` to move to the first curly brace; `v` to enter visual mode; `%` to select up to closing curly brace), then `gs` to activate interactive reordering for `{ var1, var2 }`. 

Beyond this specific TypeScript scenario, I would guess there are other unusual language constructs that are too rare for you to support explicitly, This feature might make it possible for users to work around those unusual language features and get the most of vim-swap.

**Comment by machakann** [comment]
Hi, thank you for your report. Actually this is a bug, vim-swap should recognize texts like `{ var1, var2}`, as you expected. I reproduced the problem in my environment, I will check.

At this moment, you can use visual mode but just select only inside the curly braces in this case. For example, use `vi{` to select text inside {} and start swap mode by `gs`. It should work even on now.

**Comment by machakann** [comment]
Probably this case is oK now. Please update and try.

**Comment by alexanderbird** [comment]
Thanks, that fixed it!
