### ISSUE TITLE
Space padding inside curly braces treated as part of the element

### ISSUE THREAD

**Issue by alexanderbird** [machakann/vim-swap#5]
On our project, we've chosen to have spaces between the opening curly brace and the first element, and between the last element and the last curly brace.

Expected behavior
======
1. `{ a, b }`
2. cursor over a, `g>`
3. `{ b, a }`

Observed behavior
======
1. `{ a, b }`
2. cursor over a, `g>`
3. `{ b , a}`

**Comment by machakann** [comment]
Thanks! I didn't aware of this. Now vim-swap works as you expected, please try the latest.

**Comment by alexanderbird** [comment]
Thanks @machakann, it does work as expected now :)
