### ISSUE TITLE
To replace plugins that provide argument and xml attr text objects

### ISSUE THREAD

**Issue by sassanh** [machakann/vim-swap#8]
Trying to use `vim-swap` to do what `vim-angry` and `vim-textobj-xmlattr` do while what you did on https://github.com/machakann/vim-swap/issues/7/ solved many problems one tiny problem still remains that blocked the replacement.
The problem is that `vim-swap` ignores text objects if there's only one of them in the group and goes to parent group. Consider this text:
```
[{(arg1),arg2},arg3]
```
If I try to select current argument while cursor is on arg1 it ignores `arg1` in `(arg1)` and selects `(arg1)` in `{(arg1), arg2}`. It's rational because `vim-swap` wants elements that are swappable and when a group has only one element there's nothing to swap but it doesn't work for when you're using it as a text object selector.
Is it possible to make exception for when user is using `vim-swap` as a text object selector?

**Comment by machakann** [comment]
You are right, this is strange for the textobjects. Probably it is not so difficult, I will work on it.

**Comment by machakann** [comment]
OK, please update to test the latest commit!

**Comment by sassanh** [comment]
Yeah, it's working, thanks.

**Comment by sassanh** [comment]
There's another problem, it works alright for
```
{position: 'absolute', top: '0', left: '0'}
```
but it doesn't work for:
```
{
    <CURSOR HERE>position: 'absolute', top: '0', left: '0'}
```
`via` and `vaa` selects whole construct instead of just first argument.

**Comment by machakann** [comment]
Sorry, I couldn't reproduce the case. Did you set any filetype or specific setting?

**Comment by sassanh** [comment]
It's my normal setup, let me try with a clean rc file.

**Comment by sassanh** [comment]
With a clean rc file:
```
call plug#begin()
Plug 'machakann/vim-swap'
omap ia <Plug>(swap-textobject-i)
xmap ia <Plug>(swap-textobject-i)
omap aa <Plug>(swap-textobject-a)
xmap aa <Plug>(swap-textobject-a)
call plug#end()
```
It selects only the word `position`
I'm using neovim.

**Comment by machakann** [comment]
Thank you. I don't know why but neovim-qt is down on my windows laptop. I will try it on linux tomorrow.

**Comment by sassanh** [comment]
Thanks, no rush.

**Comment by sassanh** [comment]
I tried with vim (not neovim) and it's the same.

**Comment by sassanh** [comment]
[![asciicast](https://asciinema.org/a/FFUPLJLINNXVPJZeknp3fBifp.png)](https://asciinema.org/a/FFUPLJLINNXVPJZeknp3fBifp)

Edit: embedded asciinema

**Comment by machakann** [comment]
Thank you. Finally, I reproduced and found the problem.

**Comment by machakann** [comment]
OK, please test the latest commit.

**Comment by sassanh** [comment]
Yeah, it's working now. Thanks.
